version: '3.8'
services:
  nginx:
      build:
        context: ../Services/nginx
        dockerfile: Dockerfile
      ports:
        - "80:80" # Expose NGINX on port 80 of the host
      networks:
        - your_network

  logic-gateway:
    container_name: "logic-gateway"
    build:
      context: ../Services/logic_gateway
      dockerfile: Dockerfile
    image: logic-gateway:latest
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
      REPORTS_HANDLER_HOST: "http://reports-handler"
      REPORTS_HANDLER_PORT: "10010"
      SUBSCRIPTIONS_HANDLER_HOST: "http://subscription-handler"
      SUBSCRIPTIONS_HANDLER_PORT: "10002"
      SUBSCRIPTIONS_REDIS_HOST: "http://subscription-redis"
      SUBSCRIPTIONS_REDIS_PORT: "10000"
      FLIGHTDATA_HANDLER_HOST: "http://flightdata_handler"
      FLIGHTDATA_HANDLER_PORT: "10020"
      FLIGHTDATA_RETRIEVER_HOST: "http://flightdata-retriever"
      FLIGHTDATA_RETRIEVER_PORT: "10030"

  reports-handler:
    container_name: "reports-handler"
    build:
      context: ../Services/reports-handler
      dockerfile: Dockerfile
    image: reports-handler:latest
    ports:
      - "10010:10010"
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 10010
      SPRING_DATASOURCE_URL: jdbc:mysql://Aerotelcel-MySQL:3306/Aerotelcel
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    depends_on:
      - Aerotelcel-MySQL


  flightdata-handler:
    container_name: "flightdata-handler"
    build:
      context: ../Services/flightdata_handler
      dockerfile: Dockerfile
    image: flightdata_handler:latest
    ports:
      - "10020:10020"
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 10020
      SPRING_DATASOURCE_URL: jdbc:mysql://Aerotelcel-MySQL:3306/Aerotelcel
#      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    depends_on:
      - Aerotelcel-MySQL

  flightdata-retriever:
    container_name: "flightdata-retriever"
    build:
      context: ../Services/flightdata_retriever
      dockerfile: Dockerfile
    image: flightdata_retriever:latest
    ports:
      - "10040:10040"
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_POERT: 10040
      FLIGHTDATA_HANDLER_ADDRESS: "http://flightdata-handler"
      FLIGHTDATA_HANDLER_PORT: "10020"

#  notifications-handler:
#    container_name: "notifications-handler"
#    build:
#      context: ../Services/notifications_handler
#      dockerfile: Dockerfile
#    image: notifications-handler:latest
#    ports:
#      - "10030:10030"
#    depends_on:
#      - subscription-redis
#    environment:
#      SERVER_ADDRESS: 0.0.0.0
#      SERVER_PORT: 10030
#      SUBSCRIPTION_REDIS_ADDRESS: http://subscription-redis
#      SUBSCRIPTION_REDIS_PORT: 10000

  subscription-handler:
    container_name: "subscription-handler"
    build:
      context: ../Services/subscription_handler
      dockerfile: Dockerfile
    image: subscription-handler:latest
    ports:
      - "10002:10002"
    depends_on:
      - subscription-redis
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 10002
      SUBSCRIPTION_REDIS_ADDRESS: http://subscription-redis
      SUBSCRIPTION_REDIS_PORT: 10000

  subscription-redis:
    container_name: "subscription-redis"
    build:
      context: ../Services/subscription_redis
      dockerfile: Dockerfile
    image: subscription-redis:latest
    ports:
      - "10000:10000"
    depends_on:
      - Aerotelcel-Redis
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 10000
      SPRING_DATA_REDIS_HOST: Aerotelcel-Redis
      SPRING_DATA_REDIS_PORT: 6379

  Aerotelcel-MySQL:
    container_name: "Aerotelcel-MySQL"
    image: "mysql:latest"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: Aerotelcel
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../Services/flightdata_handler/src/main/resources/airlinesdb.sql:/docker-entrypoint-initdb.d/airlinesdb.sql
      - ../Services/flightdata_handler/src/main/resources/mainairportdb.sql:/docker-entrypoint-initdb.d/mainairportdb.sql
      - ../Services/flightdata_handler/src/main/resources/flights.sql:/docker-entrypoint-initdb.d/flights.sql
      - ../Services/flightdata_handler/src/main/resources/departures.sql:/docker-entrypoint-initdb.d/departures.sql
      - ../Services/flightdata_handler/src/main/resources/arrivals.sql:/docker-entrypoint-initdb.d/arrivals.sql

  Aerotelcel-Redis:
    container_name: "Aerotelcel-Redis"
    image: "redis:alpine"
    ports:
      - "6379:6379"

networks:
  your_network:
    name: your_network
    driver: bridge