version: '3.8'
services:
  subscription_redis:
    container_name: "subscription-redis"
    build:
      context: ../Services/subscription_redis
      dockerfile: Dockerfile
    image: subscription_redis:latest
    ports:
      - "10000:10000"
    depends_on:
      - redis

  redis:
    container_name: "redis"
    image: "redis:alpine"
    ports:
      - "6379:6379"
