version: '3.8'
services:
  reports_handler:
    container_name: "reports-handler"
    build:
      context: ../Services/reports-handler
      dockerfile: Dockerfile
    image: reports-handler:latest
    ports:
      - "10010:10010"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Aerotelcel
    depends_on:
      - mysql

  subscription_handler:
    container_name: "subscription-handler"
    build:
      context: ../Services/subscription-handler
      dockerfile: Dockerfile
    image: subscription-handler:latest
    ports:
      - "10002:10002"
    depends_on:
      - subscription_redis

  subscription_redis:
    container_name: "subscription-redis"
    build:
      context: ../Services/subscription_redis
      dockerfile: Dockerfile
    image: subscription-redis:latest
    ports:
      - "10000:10000"
    depends_on:
      - redis

  mysql:
    container_name: "Aerotelcel-MySQL"
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: Aerotelcel
      MYSQL_ROOT_PASSWORD: password

  redis:
    container_name: "Aerotelcel-Redis"
    image: "redis:alpine"
    ports:
      - "6379:6379"
