name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Find Gradle projects
      id: find_projects
      run: |
        echo "::set-output name=projects::$(find ${{ github.workspace }}/Services -mindepth 1 -maxdepth 2 -type d)"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0

    - name: Grant execute permission to gradlew
      run: |
        chmod +x ${{ github.workspace }}/Services

    - name: Build with Gradle
      run: |
        for project in ${{ steps.find_projects.outputs.projects }}; do
          echo "Building $project"
          cd $project
          ./gradlew build
          cd -
        done

